// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"
#include "lvgl.h"

// CUSTOM SCREEN PROTOTYPE
void ui_screen_bant_select_init(void);
void ui_screen_order_select_init(void);
void ui_screen_operation_select_init(void);


///////////////////// VARIABLES ////////////////////


int selected_bant_id = -1;
int selected_order_id = -1;

// CUSTOM SCREENS
lv_obj_t *screen_bant;
lv_obj_t *screen_order;
lv_obj_t *screen_operation;


// SCREEN: ui_LoadingScreen
void ui_LoadingScreen_screen_init(void);
lv_obj_t * ui_LoadingScreen;
lv_obj_t * ui_merkotechLogo;
lv_obj_t * ui_loadingSpinner;
// CUSTOM VARIABLES

lv_obj_t *tileview_test;
lv_obj_t *tile_main_test;
lv_obj_t *tile_durus_test;


lv_obj_t *tileview;
lv_obj_t *tile_main;
lv_obj_t *tile_durus;
// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
lv_obj_t * ui_MainScreen;
lv_obj_t * ui_headerContainer;
lv_obj_t * ui_timeLabel;
lv_obj_t * ui_dateLabel;
lv_obj_t * ui_mainContainer;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_leftSideContainer;
lv_obj_t * ui_counterLabel;
lv_obj_t * ui_counterDataLabel2;
lv_obj_t * ui_goalLabel;
lv_obj_t * ui_goalDataLabel;
lv_obj_t * ui_dailyGoalLabel;
lv_obj_t * ui_dailyGoalDataLabel;
lv_obj_t * ui_rightSideContainer;
lv_obj_t * ui_nameLabel;
lv_obj_t * ui_surnameLabel;
lv_obj_t * ui_counterContainer;
lv_obj_t * ui_outerPanel;
lv_obj_t * ui_innerPanel;
lv_obj_t * ui_counterDataLabel;
lv_obj_t * ui_checkerBar;
lv_obj_t * ui_footerContainer;
lv_obj_t * ui_Image1;
lv_obj_t * ui_exitButton;
lv_obj_t * ui_settingsButton;
// CUSTOM VARIABLES

// SCREEN: ui_LoadingScreen
void ui_loginScreen_screen_init(void);
lv_obj_t * ui_loginScreen;

// CUSTOM VARIABLES


// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_img_dsc_t * ui_imgset_1541413707[1] = {&ui_img_441374382};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////



// UI başlatma fonksiyonu
void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);

    // Ekranları oluştur
   // Ekranları oluştur
   ui_LoadingScreen_screen_init();
   ui_MainScreen_screen_init();
   ui_loginScreen_screen_init();
   ui_screen_settings_init();

   // 💡 Bizim eklediğimiz özel ekranlar:
   ui_screen_bant_select_init();
   ui_screen_order_select_init();
   ui_screen_operation_select_init();
   ui_tileTestScreen_init();
   lv_disp_load_scr(ui_loginScreen);

    // İlk olarak Loading Screen'i göster
    //lv_disp_load_scr(ui_loginScreen);
    // 3 saniye sonra Main Screen'e geçiş yapmak için Timer oluştur
    //lv_timer_t * timer = lv_timer_create(switch_to_main_screen, 3000, NULL);
}
