// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_LoadingScreen
void ui_LoadingScreen_screen_init(void);
lv_obj_t * ui_LoadingScreen;
lv_obj_t * ui_merkotechLogo;
lv_obj_t * ui_loadingSpinner;
// CUSTOM VARIABLES


// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
lv_obj_t * ui_MainScreen;
lv_obj_t * ui_counterLabel;
void ui_event_counterData(lv_event_t * e);
lv_obj_t * ui_counterData;
lv_obj_t * ui_incBtn;
lv_obj_t * ui_Label4;
lv_obj_t * ui_decBtn;
lv_obj_t * ui_Label3;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_counterData(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_KEY) {
        _ui_label_set_property(ui_counterData, _UI_LABEL_PROPERTY_TEXT, "");
    }
}

///////////////////// SCREENS ////////////////////
// 5 saniye sonra çalışacak fonksiyon
void switch_to_main_screen(lv_timer_t * timer)
{
    // **Eğer main ekran NULL ise, önce oluştur**
    if (ui_MainScreen == NULL) {
        ui_MainScreen_screen_init();
    }
    
    // **Ana ekrana geçiş yap**
    lv_disp_load_scr(ui_MainScreen);
}

// **UI Başlatma Fonksiyonu**
void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);

    // **Önce ekranları oluştur**
    ui_LoadingScreen_screen_init();
    ui_MainScreen_screen_init();  // Bunu timer içinde de çağırabiliriz ama şimdilik oluşturduk

    ui____initial_actions0 = lv_obj_create(NULL);

    // **Başlangıçta Loading Screen'i göster**
    lv_disp_load_scr(ui_LoadingScreen);

    // **5 saniye (5000 ms) sonra `switch_to_main_screen()` fonksiyonunu çalıştır**
    lv_timer_create(switch_to_main_screen, 5000, NULL);
}