// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"



// SCREEN: ui_LoadingScreen
void ui_LoadingScreen_screen_init(void);
extern lv_obj_t * ui_LoadingScreen;
extern lv_obj_t * ui_merkotechLogo;
extern lv_obj_t * ui_loadingSpinner;
// CUSTOM VARIABLES

// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
extern lv_obj_t * ui_MainScreen;
extern lv_obj_t * ui_counterLabel;
void ui_event_counterData(lv_event_t * e);
extern lv_obj_t * ui_counterData;
extern lv_obj_t * ui_incBtn;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_decBtn;
extern lv_obj_t * ui_Label3;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_973080792);    // assets/Merkotech_logo-removebg-preview.png

//FONTS
LV_FONT_DECLARE(lv_font_custom_montserrat_100);
// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
