// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"
#include "custom_fonts/custom_fonts.h"
#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_LoadingScreen
void ui_LoadingScreen_screen_init(void);
extern lv_obj_t * ui_LoadingScreen;
extern lv_obj_t * ui_merkotechLogo;
extern lv_obj_t * ui_loadingSpinner;

// CUSTOM VARIABLES

// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
extern lv_obj_t * ui_MainScreen;
extern lv_obj_t * ui_headerContainer;
extern lv_obj_t * ui_timeLabel;
extern lv_obj_t * ui_dateLabel;
extern lv_obj_t * ui_mainContainer;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_leftSideContainer;
extern lv_obj_t * ui_counterLabel;
extern lv_obj_t * ui_counterDataLabel2;
extern lv_obj_t * ui_goalLabel;
extern lv_obj_t * ui_goalDataLabel;
extern lv_obj_t * ui_dailyGoalLabel;
extern lv_obj_t * ui_dailyGoalDataLabel;
extern lv_obj_t * ui_rightSideContainer;
extern lv_obj_t * ui_nameLabel;
extern lv_obj_t * ui_surnameLabel;
extern lv_obj_t * ui_counterContainer;
extern lv_obj_t * ui_outerPanel;
extern lv_obj_t * ui_innerPanel;
extern lv_obj_t * ui_counterDataLabel;
extern lv_obj_t * ui_checkerBar;
extern lv_obj_t * ui_footerContainer;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_exitButton;
extern lv_obj_t * ui_settingsButton;
extern lv_obj_t *ta_user;
extern lv_obj_t *ta_pass;
// CUSTOM VARIABLES

// SCREEN: ui_loginScreen
void ui_loginScreen_screen_init(void);
extern lv_obj_t * ui_loginScreen;

// CUSTOM VARIABLES

void ui_screen_bant_select_init(void);
void ui_screen_order_select_init(void);
void ui_screen_operation_select_init(void);

extern lv_obj_t * screen_bant;
extern lv_obj_t * screen_order;
extern lv_obj_t * screen_operation;

extern int selected_bant_id;
extern int selected_order_id;


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_973080792);    // assets/Merkotech_logo-removebg-preview.png
LV_IMG_DECLARE(ui_img_logout_png);    // assets/logout.png
LV_IMG_DECLARE(ui_img_setting_png);    // assets/setting.png
LV_IMG_DECLARE(ui_img_441374382);    // assets/logout-512.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
