// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui_helpers.h"
#include <string.h>
#include "ui.h"
#include <stdio.h>

/**
 * @brief  Verilen hedef saate kadar olan saniyeyi hesaplar,
 *         selected_unit_time'a böler ve sonucu label'a yazar.
 * @param  label: Sonucun yazılacağı LVGL label objesi
 * @param  hour:  Hedef saat (0–23)
 * @param  minute: Hedef dakika (0–59)
 * @param  second: Hedef saniye (0–59)
 */
void update_count_label(lv_obj_t *label, int hour, int minute, int second) {
    time_t now = time(NULL);
    struct tm now_tm = *localtime(&now);

    // hedef zamanı bugünün tarihi üzerine kur
    struct tm target_tm = now_tm;
    target_tm.tm_hour = hour;
    target_tm.tm_min  = minute;
    target_tm.tm_sec  = second;
    
    time_t target = mktime(&target_tm);
    // eğer hedef geçmişteyse, bir gün ekle
    if (target < now) {
        target_tm.tm_mday += 1;
        target = mktime(&target_tm);
    }

    // saniye farkı ve bölme işlemi
    double seconds_left = difftime(target, now);
    int count = (int)(seconds_left / selected_unit_time);
    ESP_LOGI("DEBUG", "seconds left %f\n count: %d\n selected_uniit_time %d",seconds_left, count, selected_unit_time);
    // label'a yaz
    char buf[32];
    snprintf(buf, sizeof(buf), "%d", count);
    lv_label_set_text(label, buf);
}

/**
 * @brief   Başlangıç zamanından bu yana yapılması gereken iş adedini hesaplar
 *          ve verilen label'ın metnini bu değerle günceller.
 * @param   label       Sonuç yazılacak LVGL label objesi
 * @param   start_time  İşe başlama zamanı (time(NULL) ile alınmış)
 */
void update_expected_work_label(lv_obj_t *label, time_t start_time) {
    
    time_t now = time(NULL);
    double elapsed = difftime(now, start_time);

    
    if (selected_unit_time > 0) {
        expected = (int)(elapsed / selected_unit_time);
    }

    char buf[32];
    snprintf(buf, sizeof(buf), "%d", expected);
    lv_label_set_text(label, buf);
}

/**
 * @brief   Çalışanın anlık verim değerini hesaplar 
 * @param   label       Sonuç yazılacak LVGL label objesi
 * @param   start_time  İşe başlama zamanı (time(NULL) ile alınmış)
 */
void update_efficiency(lv_obj_t *label){
    
    
}