// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_LoadingScreen_screen_init(void)
{
    ui_LoadingScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_LoadingScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LoadingScreen, lv_color_hex(0x34A2F3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LoadingScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_merkotechLogo = lv_img_create(ui_LoadingScreen);
    lv_img_set_src(ui_merkotechLogo, &ui_img_973080792);
    lv_obj_set_width(ui_merkotechLogo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_merkotechLogo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_merkotechLogo, 1);
    lv_obj_set_y(ui_merkotechLogo, -23);
    lv_obj_set_align(ui_merkotechLogo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_merkotechLogo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_merkotechLogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_loadingSpinner = lv_spinner_create(ui_LoadingScreen, 1000, 90);
    lv_obj_set_width(ui_loadingSpinner, 80);
    lv_obj_set_height(ui_loadingSpinner, 80);
    lv_obj_set_x(ui_loadingSpinner, 0);
    lv_obj_set_y(ui_loadingSpinner, 140);
    lv_obj_set_align(ui_loadingSpinner, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_loadingSpinner, LV_OBJ_FLAG_CLICKABLE);      /// Flags



}
