// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_MainScreen_screen_init(void)
{
    ui_MainScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_MainScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_MainScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_headerContainer = lv_obj_create(ui_MainScreen);
    lv_obj_remove_style_all(ui_headerContainer);
    lv_obj_set_width(ui_headerContainer, 800);
    lv_obj_set_height(ui_headerContainer, 40);
    lv_obj_set_x(ui_headerContainer, 0);
    lv_obj_set_y(ui_headerContainer, -220);
    lv_obj_set_align(ui_headerContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_headerContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_timeLabel = lv_label_create(ui_headerContainer);
    lv_obj_set_width(ui_timeLabel, 120);
    lv_obj_set_height(ui_timeLabel, 40);
    lv_obj_set_x(ui_timeLabel, -340);
    lv_obj_set_y(ui_timeLabel, 0);
    lv_obj_set_align(ui_timeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_timeLabel, "11:55");
    lv_obj_set_style_text_align(ui_timeLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_timeLabel, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_timeLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_timeLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_timeLabel, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_timeLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dateLabel = lv_label_create(ui_headerContainer);
    lv_obj_set_width(ui_dateLabel, 120);
    lv_obj_set_height(ui_dateLabel, 40);
    lv_obj_set_x(ui_dateLabel, 340);
    lv_obj_set_y(ui_dateLabel, 0);
    lv_obj_set_align(ui_dateLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dateLabel, "5/3/2025");
    lv_obj_set_style_text_align(ui_dateLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dateLabel, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_dateLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_dateLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_dateLabel, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_dateLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mainContainer = lv_obj_create(ui_MainScreen);
    lv_obj_remove_style_all(ui_mainContainer);
    lv_obj_set_width(ui_mainContainer, 800);
    lv_obj_set_height(ui_mainContainer, 350);
    lv_obj_set_x(ui_mainContainer, 0);
    lv_obj_set_y(ui_mainContainer, -20);
    lv_obj_set_align(ui_mainContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_mainContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel1 = lv_obj_create(ui_mainContainer);
    lv_obj_set_width(ui_Panel1, 800);
    lv_obj_set_height(ui_Panel1, 800);
    lv_obj_set_x(ui_Panel1, -568);
    lv_obj_set_y(ui_Panel1, 11);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel1, 800, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xDEDEDE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0xE9E0E0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Panel1, lv_color_hex(0x5AB1E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_leftSideContainer = lv_obj_create(ui_mainContainer);
    lv_obj_remove_style_all(ui_leftSideContainer);
    lv_obj_set_width(ui_leftSideContainer, 220);
    lv_obj_set_height(ui_leftSideContainer, 250);
    lv_obj_set_x(ui_leftSideContainer, -274);
    lv_obj_set_y(ui_leftSideContainer, -1);
    lv_obj_set_align(ui_leftSideContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_leftSideContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_counterLabel = lv_label_create(ui_leftSideContainer);
    lv_obj_set_width(ui_counterLabel, 160);
    lv_obj_set_height(ui_counterLabel, 35);
    lv_obj_set_x(ui_counterLabel, -30);
    lv_obj_set_y(ui_counterLabel, -80);
    lv_obj_set_align(ui_counterLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_counterLabel, "Counter");
    lv_obj_set_style_text_font(ui_counterLabel, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_counterDataLabel2 = lv_label_create(ui_leftSideContainer);
    lv_obj_set_width(ui_counterDataLabel2, 120);
    lv_obj_set_height(ui_counterDataLabel2, 30);
    lv_obj_set_x(ui_counterDataLabel2, -20);
    lv_obj_set_y(ui_counterDataLabel2, -45);
    lv_obj_set_align(ui_counterDataLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_counterDataLabel2, "100");
    lv_obj_set_style_text_font(ui_counterDataLabel2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_goalLabel = lv_label_create(ui_leftSideContainer);
    lv_obj_set_width(ui_goalLabel, 160);
    lv_obj_set_height(ui_goalLabel, 35);
    lv_obj_set_x(ui_goalLabel, -30);
    lv_obj_set_y(ui_goalLabel, 80);
    lv_obj_set_align(ui_goalLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_goalLabel, "Goal");
    lv_obj_set_style_text_font(ui_goalLabel, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_goalDataLabel = lv_label_create(ui_leftSideContainer);
    lv_obj_set_width(ui_goalDataLabel, 120);
    lv_obj_set_height(ui_goalDataLabel, 30);
    lv_obj_set_x(ui_goalDataLabel, -20);
    lv_obj_set_y(ui_goalDataLabel, 35);
    lv_obj_set_align(ui_goalDataLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_goalDataLabel, "2000");
    lv_obj_set_style_text_font(ui_goalDataLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dailyGoalLabel = lv_label_create(ui_leftSideContainer);
    lv_obj_set_width(ui_dailyGoalLabel, 160);
    lv_obj_set_height(ui_dailyGoalLabel, 35);
    lv_obj_set_x(ui_dailyGoalLabel, -30);
    lv_obj_set_y(ui_dailyGoalLabel, 0);
    lv_obj_set_align(ui_dailyGoalLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dailyGoalLabel, "Daily Goal");
    lv_obj_set_style_text_font(ui_dailyGoalLabel, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dailyGoalDataLabel = lv_label_create(ui_leftSideContainer);
    lv_obj_set_width(ui_dailyGoalDataLabel, 120);
    lv_obj_set_height(ui_dailyGoalDataLabel, 30);
    lv_obj_set_x(ui_dailyGoalDataLabel, -20);
    lv_obj_set_y(ui_dailyGoalDataLabel, 115);
    lv_obj_set_align(ui_dailyGoalDataLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dailyGoalDataLabel, "2000");
    lv_obj_set_style_text_font(ui_dailyGoalDataLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rightSideContainer = lv_obj_create(ui_mainContainer);
    lv_obj_remove_style_all(ui_rightSideContainer);
    lv_obj_set_width(ui_rightSideContainer, 200);
    lv_obj_set_height(ui_rightSideContainer, 300);
    lv_obj_set_x(ui_rightSideContainer, 290);
    lv_obj_set_y(ui_rightSideContainer, 0);
    lv_obj_set_align(ui_rightSideContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_rightSideContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_nameLabel = lv_label_create(ui_rightSideContainer);
    lv_obj_set_width(ui_nameLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_nameLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_nameLabel, 50);
    lv_obj_set_y(ui_nameLabel, 110);
    lv_obj_set_align(ui_nameLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_nameLabel, "Yusuf\n");
    lv_obj_set_style_text_font(ui_nameLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_surnameLabel = lv_label_create(ui_rightSideContainer);
    lv_obj_set_width(ui_surnameLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_surnameLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_surnameLabel, 50);
    lv_obj_set_y(ui_surnameLabel, 130);
    lv_obj_set_align(ui_surnameLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_surnameLabel, "CAKIRCA");
    lv_obj_set_style_text_font(ui_surnameLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_counterContainer = lv_obj_create(ui_mainContainer);
    lv_obj_remove_style_all(ui_counterContainer);
    lv_obj_set_width(ui_counterContainer, 300);
    lv_obj_set_height(ui_counterContainer, 300);
    lv_obj_set_x(ui_counterContainer, 30);
    lv_obj_set_y(ui_counterContainer, -26);
    lv_obj_set_align(ui_counterContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_counterContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_outerPanel = lv_obj_create(ui_counterContainer);
    lv_obj_set_width(ui_outerPanel, 300);
    lv_obj_set_height(ui_outerPanel, 300);
    lv_obj_set_align(ui_outerPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_outerPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_outerPanel, 300, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_outerPanel, lv_color_hex(0x0CE92F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_outerPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_innerPanel = lv_obj_create(ui_outerPanel);
    lv_obj_set_width(ui_innerPanel, 200);
    lv_obj_set_height(ui_innerPanel, 200);
    lv_obj_set_align(ui_innerPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_innerPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_innerPanel, 300, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_counterDataLabel = lv_label_create(ui_outerPanel);
    lv_obj_set_width(ui_counterDataLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_counterDataLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_counterDataLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_counterDataLabel, "100");
    lv_obj_set_style_text_font(ui_counterDataLabel, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_checkerBar = lv_bar_create(ui_mainContainer);
    lv_bar_set_range(ui_checkerBar, 0, 5);
    lv_bar_set_value(ui_checkerBar, 4, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_checkerBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_checkerBar, 200);
    lv_obj_set_height(ui_checkerBar, 30);
    lv_obj_set_x(ui_checkerBar, 30);
    lv_obj_set_y(ui_checkerBar, 150);
    lv_obj_set_align(ui_checkerBar, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_checkerBar, lv_color_hex(0x0CE92F), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_checkerBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_footerContainer = lv_obj_create(ui_MainScreen);
    lv_obj_remove_style_all(ui_footerContainer);
    lv_obj_set_width(ui_footerContainer, 800);
    lv_obj_set_height(ui_footerContainer, 80);
    lv_obj_set_x(ui_footerContainer, 0);
    lv_obj_set_y(ui_footerContainer, 200);
    lv_obj_set_align(ui_footerContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_footerContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_footerContainer, lv_color_hex(0x00A8FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_footerContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_footerContainer);
    lv_img_set_src(ui_Image1, &ui_img_973080792);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 474
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 527
    lv_obj_set_x(ui_Image1, 0);
    lv_obj_set_y(ui_Image1, 7);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image1, 50);

    ui_exitButton = lv_btn_create(ui_footerContainer);
    lv_obj_set_width(ui_exitButton, 60);
    lv_obj_set_height(ui_exitButton, 60);
    lv_obj_set_x(ui_exitButton, 360);
    lv_obj_set_y(ui_exitButton, 0);
    lv_obj_set_align(ui_exitButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_exitButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_exitButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_exitButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_exitButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_exitButton, &ui_img_logout_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settingsButton = lv_btn_create(ui_footerContainer);
    lv_obj_set_width(ui_settingsButton, 60);
    lv_obj_set_height(ui_settingsButton, 60);
    lv_obj_set_x(ui_settingsButton, -360);
    lv_obj_set_y(ui_settingsButton, 0);
    lv_obj_set_align(ui_settingsButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_settingsButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_settingsButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_settingsButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_settingsButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_settingsButton, &ui_img_setting_png, LV_PART_MAIN | LV_STATE_DEFAULT);


}
