// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

#include "ui_helpers.h"
#include "esp_log.h"

static void show_pin_popup(void);
static void kb_event_cb(lv_event_t *e);
static void pin_entered_cb(lv_event_t *e);
static lv_obj_t *pin_popup;
static lv_obj_t *pin_ta;

// ————— Globals —————
static bool timer_started = false;  // timer’ın bir kez başlatıldığını takip edecek

// ————— Prototipler —————
static void refresh_main_screen(void);
static void screen_main_loaded_cb(lv_event_t *e);
static void update_work_timer_cb(lv_timer_t *timer);
// ————— Çalışma için gereken global değişkenler —————
static lv_obj_t *durus_overlay;
static lv_obj_t *durus_popup;
static lv_obj_t *durus_timer_label;
static lv_timer_t *durus_timer_handle;
static time_t durus_start_time;

// ————— Sayaç güncelleme callback’i —————
static void durus_timer_cb(lv_timer_t *timer) {
    (void)timer;
    time_t now = time(NULL);
    uint32_t elapsed = (uint32_t)(now - durus_start_time);
    uint32_t mins = elapsed / 60;
    uint32_t secs = elapsed % 60;
    char buf[16];
    lv_snprintf(buf, sizeof(buf), "%02lu:%02lu", mins, secs);
    lv_label_set_text(durus_timer_label, buf);
}

// ————— Bitir butonu callback’i —————
static void finish_durus_cb(lv_event_t *e) {
    // Sayaçı durdur ve popup’ı kapat
    lv_timer_del(durus_timer_handle);
    lv_obj_del(durus_overlay);
    // Gerekirse buraya ana ekrana dönme kodu ekleyin (zaten popup silindikten sonra tileview açık kalır)
}

// ————— Popup gösterme fonksiyonu —————
static void show_durus_popup(lv_event_t *e) {
    // Overlay
    lv_obj_t *scr = lv_layer_top();
    durus_overlay = lv_obj_create(scr);
    lv_obj_set_size(durus_overlay, 800, 480);
    lv_obj_set_style_bg_color(durus_overlay, lv_color_black(), 0);
    lv_obj_set_style_bg_opa(durus_overlay, LV_OPA_50, 0);
    lv_obj_clear_flag(durus_overlay, LV_OBJ_FLAG_SCROLLABLE);

    // Popup kutusu
    durus_popup = lv_obj_create(durus_overlay);
    lv_obj_set_size(durus_popup, 300, 180);
    lv_obj_center(durus_popup);
    lv_obj_set_style_bg_color(durus_popup, lv_color_hex(0xFFFFFF), 0);
    lv_obj_set_style_radius(durus_popup, 8, 0);

    // Başlık
    lv_obj_t *title = lv_label_create(durus_popup);
    lv_label_set_text(title, "Durus Basladi");
    lv_obj_align(title, LV_ALIGN_TOP_MID, 0, 10);

    // Sayaç label’ı
    durus_timer_label = lv_label_create(durus_popup);
    lv_label_set_text(durus_timer_label, "00:00");
    lv_obj_align(durus_timer_label, LV_ALIGN_CENTER, 0, -10);
    lv_obj_set_style_text_font(durus_timer_label, &lv_font_montserrat_26, 0);

    // Bitir butonu
    lv_obj_t *finish_btn = lv_btn_create(durus_popup);
    lv_obj_set_size(finish_btn, 100, 40);
    lv_obj_align(finish_btn, LV_ALIGN_BOTTOM_MID, 0, -10);
    lv_obj_add_event_cb(finish_btn, finish_durus_cb, LV_EVENT_CLICKED, NULL);
    lv_obj_t *finish_lbl = lv_label_create(finish_btn);
    lv_label_set_text(finish_lbl, "Bitir");
    lv_obj_center(finish_lbl);

    // Sayaç başlangıcı
    durus_start_time = time(NULL);
    durus_timer_handle = lv_timer_create(durus_timer_cb, 1000, NULL);
}
// ————— Timer Callback —————
static void update_work_timer_cb(lv_timer_t *timer) {
    (void)timer;
    update_expected_work_label(ui_performanceDataLabel, login_timestamp);
    refresh_main_screen();
}

// ————— Screen Loaded Callback —————
static void screen_main_loaded_cb(lv_event_t *e) {
    (void)e;
    ESP_LOGI("debug", "screen_main_loaded_cb tetiklendi");
    
    
        login_timestamp = time(NULL);  // Timer’ı başlat
        lv_timer_create(update_work_timer_cb, 1000, NULL);  // Timer'ı başlat
        timer_started = true;
        ESP_LOGI("debug", "Timer başlatıldı");
    
    refresh_main_screen();  // Ekranı her yüklenince güncelle
}

// ————— Refresh Fonksiyonu —————
static void refresh_main_screen(void) {
    update_expected_work_label(ui_performanceDataLabel, login_timestamp);
    update_count_label(ui_goalDataLabel, 18, 0, 0);  // Örnek olarak 18:00
    

    time_t now = time(NULL);
    struct tm *tm = localtime(&now);
    char time_buf[16], date_buf[16];
    strftime(time_buf, sizeof(time_buf), "%H:%M", tm);
    strftime(date_buf, sizeof(date_buf), "%-m/%-d/%Y", tm);
    lv_label_set_text(ui_timeLabel, time_buf);
    lv_label_set_text(ui_dateLabel, date_buf);
    ESP_LOGI("Debug","Timer çalıştı, debug deneme");
}


static void cancel_btn_event_cb(lv_event_t *e) {
    if (pin_popup) {
        lv_obj_del(pin_popup);
        pin_popup = NULL;
    }
}


static void show_pin_popup(void) {
    lv_obj_t *top_layer = lv_layer_top();

    pin_popup = lv_obj_create(top_layer);
    lv_obj_set_size(pin_popup, 300, 200);
    lv_obj_center(pin_popup);
    lv_obj_set_style_bg_color(pin_popup, lv_color_hex(0xFFFFFF), 0);
    lv_obj_set_style_radius(pin_popup, 10, 0);
    lv_obj_set_style_pad_all(pin_popup, 10, 0);

    lv_obj_t *label = lv_label_create(pin_popup);
    lv_label_set_text(label, "PIN Kodu:");
    lv_obj_align(label, LV_ALIGN_TOP_MID, 0, 10);

    pin_ta = lv_textarea_create(pin_popup);
    lv_obj_set_size(pin_ta, 200, 50);
    lv_textarea_set_password_mode(pin_ta, true);
    lv_obj_align(pin_ta, LV_ALIGN_CENTER, 0, -20);

    lv_obj_t *kb = lv_keyboard_create(top_layer);
    lv_keyboard_set_mode(kb, LV_KEYBOARD_MODE_NUMBER);
    lv_keyboard_set_textarea(kb, pin_ta);
    lv_obj_add_event_cb(kb, kb_event_cb, LV_EVENT_ALL, pin_ta);

    // Giriş butonu
    lv_obj_t *ok_btn = lv_btn_create(pin_popup);
    lv_obj_set_size(ok_btn, 100, 40);
    lv_obj_align(ok_btn, LV_ALIGN_BOTTOM_LEFT, 10, -10);
    lv_obj_add_event_cb(ok_btn, pin_entered_cb, LV_EVENT_CLICKED, NULL);
    lv_obj_t *ok_lbl = lv_label_create(ok_btn);
    lv_label_set_text(ok_lbl, "Giris");
    lv_obj_center(ok_lbl);

    // İptal butonu
    lv_obj_t *cancel_btn = lv_btn_create(pin_popup);
    lv_obj_set_size(cancel_btn, 100, 40);
    lv_obj_align(cancel_btn, LV_ALIGN_BOTTOM_RIGHT, -10, -10);
    lv_obj_add_event_cb(cancel_btn, cancel_btn_event_cb, LV_EVENT_CLICKED, NULL);
    lv_obj_t *cancel_lbl = lv_label_create(cancel_btn);
    lv_label_set_text(cancel_lbl, "Iptal");
    lv_obj_center(cancel_lbl);
}



static void pin_entered_cb(lv_event_t *e) {
    const char *pin = lv_textarea_get_text(pin_ta);
    if (strcmp(pin, "1234") == 0) {
        lv_obj_del(pin_popup);
        lv_disp_load_scr(screen_settings);
    } else {
        lv_label_set_text(lv_label_create(pin_popup), "Hatali PIN!");
    }
}

static void kb_event_cb(lv_event_t * e) {
    lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t * ta = lv_event_get_user_data(e);

    if (code == LV_EVENT_READY || code == LV_EVENT_CANCEL) {
        lv_obj_del(lv_event_get_target(e)); // Klavyeyi kaldır
    }
}

static void settings_btn_event_cb(lv_event_t *e) {
    show_pin_popup(); 
}


// Popup için overlay tanımı
static lv_obj_t *popup_overlay;

// Prototipler
static void show_exit_confirmation_popup(void);
static void confirm_logout_cb(lv_event_t *e);
static void cancel_logout_cb(lv_event_t *e);

//EVENT CB
static void exit_btn_event_cb(lv_event_t * e) {
    // Oturumu sıfırlayabilirsin, değişkenleri temizleyebilirsin vs.
    show_exit_confirmation_popup(); 
}

void call_maintenance_cb(lv_event_t *e) {
    // Buraya HTTP isteği gönderen kodu yazabilirsin
    
    // Geçici simülasyon: butonu disable et
    lv_obj_add_state(lv_event_get_target(e), LV_STATE_DISABLED);
}

static void confirm_logout_cb(lv_event_t *e) {
    lv_obj_del(popup_overlay);  // popup ve overlay temizle
    selected_bant_id = -1;
    selected_cut_count = -1;
    selected_order_id = -1;
    selected_unit_time = -1;
    selected_unit_time_tol = -1;
    counter = 0;
    lv_label_set_text(ui_counterDataLabel,"0");
    lv_textarea_set_text(ta_user, "");
    lv_textarea_set_text(ta_pass, "");
    lv_disp_load_scr(ui_loginScreen);  // login ekranına dön
}

static void cancel_logout_cb(lv_event_t *e) {
    lv_obj_del(popup_overlay);  // popup'ı kapat
}

static void show_exit_confirmation_popup(void) {
    lv_obj_t *top_layer = lv_layer_top();
    struct tm tm_info;
    localtime_r(&login_timestamp, &tm_info);
    ESP_LOGW("DEBUG", "login_timestamp (main screen): %04d-%02d-%02d %02d:%02d:%02d",
    tm_info.tm_year + 1900,
    tm_info.tm_mon  + 1,
    tm_info.tm_mday,
    tm_info.tm_hour,
    tm_info.tm_min,
    tm_info.tm_sec
);
    //update_expected_work_label(ui_dailyGoalDataLabel, login_timestamp);
    popup_overlay = lv_obj_create(top_layer);
    lv_obj_set_size(popup_overlay, 800, 480);
    lv_obj_set_style_bg_color(popup_overlay, lv_color_hex(0x000000), 0);
    lv_obj_set_style_bg_opa(popup_overlay, LV_OPA_50, 0);
    lv_obj_clear_flag(popup_overlay, LV_OBJ_FLAG_SCROLLABLE);

    lv_obj_t *popup = lv_obj_create(popup_overlay);
    lv_obj_set_size(popup, 300, 180);
    lv_obj_center(popup);
    lv_obj_set_style_bg_color(popup, lv_color_hex(0xFFFFFF), 0);
    lv_obj_set_style_radius(popup, 12, 0);
    lv_obj_set_style_shadow_width(popup, 20, 0);

    lv_obj_t *label = lv_label_create(popup);
    lv_label_set_text(label, "Cikmak istedigine emin misin?");
    lv_obj_align(label, LV_ALIGN_TOP_MID, 0, 20);

    lv_obj_t *btn_yes = lv_btn_create(popup);
    lv_obj_set_size(btn_yes, 100, 40);
    lv_obj_align(btn_yes, LV_ALIGN_BOTTOM_LEFT, 10, -10);
    lv_obj_add_event_cb(btn_yes, confirm_logout_cb, LV_EVENT_CLICKED, NULL);
    lv_label_set_text(lv_label_create(btn_yes), "Evet");

    lv_obj_t *btn_no = lv_btn_create(popup);
    lv_obj_set_size(btn_no, 100, 40);
    lv_obj_align(btn_no, LV_ALIGN_BOTTOM_RIGHT, -10, -10);
    lv_obj_add_event_cb(btn_no, cancel_logout_cb, LV_EVENT_CLICKED, NULL);
    lv_label_set_text(lv_label_create(btn_no), "Hayir");
}



void ui_screen_main_init(void)
{      
    struct tm tm_info;
        localtime_r(&login_timestamp, &tm_info);
    ESP_LOGW("DEBUG",
        "login_timestamp (main screen): %04d-%02d-%02d %02d:%02d:%02d",
        tm_info.tm_year + 1900,
        tm_info.tm_mon  + 1,
        tm_info.tm_mday,
        tm_info.tm_hour,
        tm_info.tm_min,
        tm_info.tm_sec
    );
    tileview = lv_tileview_create(NULL);
    lv_obj_set_size(tileview, 800, 480);
    ESP_LOGI("Debug","main screen init");
    tile_main = lv_tileview_add_tile(tileview, 0, 0, LV_DIR_BOTTOM);  // Main screen olarak kullanılacak tile
    lv_obj_add_event_cb(tile_main, screen_main_loaded_cb, LV_EVENT_SCREEN_LOADED, NULL);
    

    ui_headerContainer = lv_obj_create(tile_main);
    lv_obj_remove_style_all(ui_headerContainer);
    lv_obj_set_width(ui_headerContainer, 800);
    lv_obj_set_height(ui_headerContainer, 40);
    
    lv_obj_set_x(ui_headerContainer, 0);
    lv_obj_set_y(ui_headerContainer, -220);
    lv_obj_set_align(ui_headerContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_headerContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_timeLabel = lv_label_create(ui_headerContainer);
    lv_obj_set_width(ui_timeLabel, 120);
    lv_obj_set_height(ui_timeLabel, 40);
    lv_obj_set_x(ui_timeLabel, -340);
    lv_obj_set_y(ui_timeLabel, 0);
    lv_obj_set_align(ui_timeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_timeLabel, "11:55");
    lv_obj_set_style_text_align(ui_timeLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_timeLabel, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_timeLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_timeLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_timeLabel, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_timeLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dateLabel = lv_label_create(ui_headerContainer);
    lv_obj_set_width(ui_dateLabel, 120);
    lv_obj_set_height(ui_dateLabel, 40);
    lv_obj_set_x(ui_dateLabel, 330);
    lv_obj_set_y(ui_dateLabel, 0);
    lv_obj_set_align(ui_dateLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dateLabel, "5/3/2025");
    lv_obj_set_style_text_align(ui_dateLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dateLabel, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_dateLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_dateLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_dateLabel, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_dateLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mainContainer = lv_obj_create(tile_main);
    lv_obj_remove_style_all(ui_mainContainer);
    lv_obj_set_width(ui_mainContainer, 800);
    lv_obj_set_height(ui_mainContainer, 440);
    lv_obj_set_x(ui_mainContainer, 0);
    lv_obj_set_y(ui_mainContainer, 20); 
    lv_obj_set_align(ui_mainContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_mainContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel1 = lv_obj_create(ui_mainContainer);
    lv_obj_set_width(ui_Panel1, 800);
    lv_obj_set_height(ui_Panel1, 800);
    lv_obj_set_x(ui_Panel1, -568);
    lv_obj_set_y(ui_Panel1, 11);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel1, 800, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xDEDEDE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0xE9E0E0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Panel1, lv_color_hex(0x5AB1E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_leftSideContainer = lv_obj_create(ui_mainContainer);
    lv_obj_remove_style_all(ui_leftSideContainer);
    lv_obj_set_width(ui_leftSideContainer, 220);
    lv_obj_set_height(ui_leftSideContainer, 350);
    lv_obj_set_x(ui_leftSideContainer, -274);
    lv_obj_set_y(ui_leftSideContainer, -1);
    lv_obj_set_align(ui_leftSideContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_leftSideContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_performanceLabel = lv_label_create(ui_leftSideContainer);
    lv_obj_set_width(ui_performanceLabel, 220);
    lv_obj_set_height(ui_performanceLabel, 35);
    lv_obj_set_x(ui_performanceLabel, 0);
    lv_obj_set_y(ui_performanceLabel, -140);
    lv_obj_set_align(ui_performanceLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_performanceLabel, "Performans");
    lv_obj_set_style_text_font(ui_performanceLabel, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_performanceDataLabel = lv_label_create(ui_leftSideContainer);
    lv_obj_set_width(ui_performanceDataLabel, 120);
    lv_obj_set_height(ui_performanceDataLabel, 30);
    lv_obj_set_x(ui_performanceDataLabel, -20);
    lv_obj_set_y(ui_performanceDataLabel, -105);
    lv_obj_set_align(ui_performanceDataLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_performanceDataLabel, "0");
    lv_obj_set_style_text_font(ui_performanceDataLabel, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_goalLabel = lv_label_create(ui_leftSideContainer);
    lv_obj_set_width(ui_goalLabel, 220);
    lv_obj_set_height(ui_goalLabel, 35);
    lv_obj_set_x(ui_goalLabel, 0);
    lv_obj_set_y(ui_goalLabel, 20);
    lv_obj_set_align(ui_goalLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_goalLabel, "Gunluk Hedef");
    lv_obj_set_style_text_font(ui_goalLabel, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_goalDataLabel = lv_label_create(ui_leftSideContainer);
    lv_obj_set_width(ui_goalDataLabel, 120);
    lv_obj_set_height(ui_goalDataLabel, 30);
    lv_obj_set_x(ui_goalDataLabel, -20);
    lv_obj_set_y(ui_goalDataLabel, 55);
    lv_obj_set_align(ui_goalDataLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_goalDataLabel, "0");
    lv_obj_set_style_text_font(ui_goalDataLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dailyGoalLabel = lv_label_create(ui_leftSideContainer);
    lv_obj_set_width(ui_dailyGoalLabel, 220);
    lv_obj_set_height(ui_dailyGoalLabel, 35);
    lv_obj_set_x(ui_dailyGoalLabel, 0);
    lv_obj_set_y(ui_dailyGoalLabel, -60);
    lv_obj_set_align(ui_dailyGoalLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dailyGoalLabel, "Anlik Hedef");
    lv_obj_set_style_text_font(ui_dailyGoalLabel, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dailyGoalDataLabel = lv_label_create(ui_leftSideContainer);
    lv_obj_set_width(ui_dailyGoalDataLabel, 120);
    lv_obj_set_height(ui_dailyGoalDataLabel, 30);
    lv_obj_set_x(ui_dailyGoalDataLabel, -20);
    lv_obj_set_y(ui_dailyGoalDataLabel, -25);
    lv_obj_set_align(ui_dailyGoalDataLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dailyGoalDataLabel, "0");
    lv_obj_set_style_text_font(ui_dailyGoalDataLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rightSideContainer = lv_obj_create(ui_mainContainer);
    lv_obj_remove_style_all(ui_rightSideContainer);
    lv_obj_set_width(ui_rightSideContainer, 200);
    lv_obj_set_height(ui_rightSideContainer, 300);
    lv_obj_set_x(ui_rightSideContainer, 290);
    lv_obj_set_y(ui_rightSideContainer, 0);
    lv_obj_set_align(ui_rightSideContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_rightSideContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_nameLabel = lv_label_create(ui_rightSideContainer);
    lv_obj_set_width(ui_nameLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_nameLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_nameLabel, 50);
    lv_obj_set_y(ui_nameLabel, 110);
    lv_obj_set_align(ui_nameLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_nameLabel, "Yusuf\n");
    lv_obj_set_style_text_font(ui_nameLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_surnameLabel = lv_label_create(ui_rightSideContainer);
    lv_obj_set_width(ui_surnameLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_surnameLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_surnameLabel, 50);
    lv_obj_set_y(ui_surnameLabel, 130);
    lv_obj_set_align(ui_surnameLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_surnameLabel, "CAKIRCA");
    lv_obj_set_style_text_font(ui_surnameLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_counterContainer = lv_obj_create(ui_mainContainer);
    lv_obj_remove_style_all(ui_counterContainer);
    lv_obj_set_width(ui_counterContainer, 300);
    lv_obj_set_height(ui_counterContainer, 300);
    lv_obj_set_x(ui_counterContainer, 30);
    lv_obj_set_y(ui_counterContainer, -26);
    lv_obj_set_align(ui_counterContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_counterContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_outerPanel = lv_obj_create(ui_counterContainer);
    lv_obj_set_width(ui_outerPanel, 300);
    lv_obj_set_height(ui_outerPanel, 300);
    lv_obj_set_align(ui_outerPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_outerPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_outerPanel, 300, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_outerPanel, lv_color_hex(0x0CE92F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_outerPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_innerPanel = lv_obj_create(ui_outerPanel);
    lv_obj_set_width(ui_innerPanel, 200);
    lv_obj_set_height(ui_innerPanel, 200);
    lv_obj_set_align(ui_innerPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_innerPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_innerPanel, 300, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_counterDataLabel = lv_label_create(ui_outerPanel);
    lv_obj_set_width(ui_counterDataLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_counterDataLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_counterDataLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_counterDataLabel, "0");
    lv_obj_set_style_text_font(ui_counterDataLabel, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PulseLabel = lv_label_create(ui_innerPanel);
    lv_obj_set_width(ui_PulseLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PulseLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PulseLabel, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_PulseLabel, "0");
    lv_obj_set_style_text_font(ui_PulseLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_checkerBar = lv_bar_create(ui_mainContainer);
    
    lv_bar_set_start_value(ui_checkerBar, 5, LV_ANIM_OFF);
    lv_obj_set_width(ui_checkerBar, 30);
    lv_obj_set_height(ui_checkerBar, 200);
    lv_obj_set_x(ui_checkerBar, 200);
    lv_obj_set_y(ui_checkerBar, -30);
    lv_obj_set_align(ui_checkerBar, LV_ALIGN_CENTER);
    lv_bar_set_range(ui_checkerBar, 0, 5); 
    lv_bar_set_value(ui_checkerBar, 5, LV_ANIM_OFF);  // Bar tam dolu başlasın

    lv_obj_set_style_bg_color(ui_checkerBar, lv_color_hex(0x0CE92F), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_checkerBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_exitButton = lv_btn_create(tile_main);
    lv_obj_set_size(ui_exitButton, 60, 60);
    lv_obj_align(ui_exitButton, LV_ALIGN_BOTTOM_RIGHT, -10, -10);
    lv_obj_set_style_bg_img_src(ui_exitButton, &ui_img_logout_png, LV_PART_MAIN);
    lv_obj_add_event_cb(ui_exitButton, exit_btn_event_cb, LV_EVENT_CLICKED, NULL);
    lv_obj_set_style_bg_color(ui_exitButton, lv_color_hex(0xffffff), LV_PART_MAIN);
    // Durus ekranı tile'ı - en başa taşındı
    tile_durus = lv_tileview_add_tile(tileview, 0, 1, LV_DIR_TOP);

    // Footer (Artık tile_durus altına eklenecek ve görünür olacak)
    ui_footerContainer = lv_obj_create(tile_durus);
    lv_obj_remove_style_all(ui_footerContainer);
    lv_obj_set_size(ui_footerContainer, 800, 80);
    lv_obj_align(ui_footerContainer, LV_ALIGN_BOTTOM_MID, 0, 0);
    lv_obj_clear_flag(ui_footerContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(ui_footerContainer, lv_color_hex(0x00A8FF), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_footerContainer, 255, LV_PART_MAIN);

    ui_Image1 = lv_img_create(ui_footerContainer);
    lv_img_set_src(ui_Image1, &ui_img_973080792);
    lv_obj_align(ui_Image1, LV_ALIGN_CENTER, 0, 7);
    lv_img_set_zoom(ui_Image1, 50);
    
    ui_settingsButton = lv_btn_create(ui_footerContainer);
    lv_obj_set_size(ui_settingsButton, 60, 60);
    lv_obj_align(ui_settingsButton, LV_ALIGN_LEFT_MID, 10, 0);
    lv_obj_set_style_bg_img_src(ui_settingsButton, &ui_img_setting_png, LV_PART_MAIN);
    lv_obj_add_event_cb(ui_settingsButton, settings_btn_event_cb, LV_EVENT_CLICKED, NULL);
    lv_obj_set_style_bg_color(ui_settingsButton, lv_color_hex(0xffffff), LV_PART_MAIN);

    // ————— Duruşlar kısmı: 4 buton —————
    int btn_w = 320;
    int btn_h = 145;
    int spacing_x = 20;
    int spacing_y = 20;
    int start_x = 60;
    int start_y = 60;

    // Buton 1
    lv_obj_t *btn1 = lv_btn_create(tile_durus);
    lv_obj_set_size(btn1, btn_w, btn_h);
    lv_obj_align(btn1, LV_ALIGN_TOP_LEFT, start_x, start_y);
    lv_obj_set_style_bg_color(btn1, lv_color_hex(0x457b9d), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(btn1, LV_OPA_COVER, LV_PART_MAIN);
    lv_obj_add_event_cb(btn1, show_durus_popup, LV_EVENT_CLICKED, NULL);
    lv_obj_t *lbl1 = lv_label_create(btn1);
    lv_label_set_text(lbl1, "BAKIM");
    lv_obj_center(lbl1);
    lv_obj_set_style_text_font(lbl1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Buton 2
    lv_obj_t *btn2 = lv_btn_create(tile_durus);
    lv_obj_set_size(btn2, btn_w, btn_h);
    lv_obj_align(btn2, LV_ALIGN_TOP_LEFT,
                start_x + (btn_w + spacing_x),
                start_y);
    lv_obj_set_style_bg_color(btn2, lv_color_hex(0xe23838), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(btn2, LV_OPA_COVER, LV_PART_MAIN);
    lv_obj_t *lbl2 = lv_label_create(btn2);
    lv_label_set_text(lbl2, "YEMEK");
    lv_obj_center(lbl2);
    lv_obj_set_style_text_font(lbl2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Buton 3
    lv_obj_t *btn3 = lv_btn_create(tile_durus);
    lv_obj_set_size(btn3, btn_w, btn_h);
    lv_obj_align(btn3, LV_ALIGN_TOP_LEFT,
                start_x,
                start_y + (btn_h + spacing_y));
    lv_obj_set_style_bg_color(btn3, lv_color_hex(0xf78200), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(btn3, LV_OPA_COVER, LV_PART_MAIN);
    lv_obj_t *lbl3 = lv_label_create(btn3);
    lv_label_set_text(lbl3, "KISISEL IHTIYAC");
    lv_obj_center(lbl3);
    lv_obj_set_style_text_font(lbl3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Buton 4
    lv_obj_t *btn4 = lv_btn_create(tile_durus);
    lv_obj_set_size(btn4, btn_w, btn_h);
    lv_obj_align(btn4, LV_ALIGN_TOP_LEFT,
                start_x + (btn_w + spacing_x),
                start_y + (btn_h + spacing_y));
    lv_obj_set_style_bg_color(btn4, lv_color_hex(0x66b447), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(btn4, LV_OPA_COVER, LV_PART_MAIN);
    lv_obj_t *lbl4 = lv_label_create(btn4);
    lv_label_set_text(lbl4, "DURUS 4");
    lv_obj_center(lbl4);
    lv_obj_set_style_text_font(lbl4, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_disp_load_scr(tileview);  // Ekrana tileview'i yükle
}
